server:
  port: 21000
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"

spring:
  application:
    name: GatewayApp
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: catalog-service
        uri: lb://catalog-service
        predicates:
        - Path=/catalog/**
        filters:
        - RewritePath=/catalog/(?<path>.*), /$\{path}
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  cache:
    disabled: true
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi-3-1
